### ISSUE TITLE
Release 1.3.1 release Tag

### ISSUE THREAD

**Issue by precurse** [OpenConext/OpenConext-oidc#7]
Hello,

I noticed that version 1.3.1 was referenced in the git history, but the tag wasn't pushed to the repo for our build system to pick up. Would you mind push the tag to the repo as well?

Thanks in advance!
Andrew

**Comment by oharsta** [comment]
Tagged v1.3.1 and v1.3.2. Picked up by GitHub and uploaded to https://build.openconext.org/repository/public/releases/org/openconext/oidc-server/1.3.x
